### ISSUE TITLE
make_wikipedia in getting_started.md

### ISSUE THREAD

**Issue by leeparkuky** [allenai/dolma#125]
The code for running make_wikipedia needs to be edited. The one currently in the document

python scripts/make_wikipedia.py \
  --output wikipedia \
  --languages simple \
  --date 20231001 \
  --lang simple \
  --num_processes 16

should be written as below:

python scripts/make_wikipedia.py \
  --output wikipedia \
  --date 20231001 \
  --lang simple \
  --processes 16

**Comment by soldni** [comment]
Thank you for the report! Would you have bandwidth for a which PR?

**Comment by RohitRathore1** [comment]
@soldni I have already submitted that PR which is resolving this issue.

**Comment by soldni** [comment]
closing since fixed in #117. Thanks again @RohitRathore1!
