### ISSUE TITLE
Issue with ring tokenizer

### ISSUE THREAD

**Issue by davidbrandfonbrener** [allenai/dolma#175]
[This line](https://github.com/allenai/dolma/blob/64886d9db15bd99acea9e28740ae20a510875dfb/python/dolma/tokenizer/executor.py#L129) seems to throw an error when `ring_size < len(source_paths)` for division by 0.

Basically it seems that `len(tokenizer_ring)` will be decremented [here](https://github.com/allenai/dolma/blob/64886d9db15bd99acea9e28740ae20a510875dfb/python/dolma/tokenizer/executor.py#L144). The inner loop is [broken](https://github.com/allenai/dolma/blob/64886d9db15bd99acea9e28740ae20a510875dfb/python/dolma/tokenizer/executor.py#L149), but the outer loop keeps going and divides by 0.

I'm not exactly sure what the right fix is, and it seems things work fine as long as `ring_size * processes >= num_files`. Any clarity here would be appreciated, thanks!

**Comment by soldni** [comment]
Hey @davidbrandfonbrener, thank you for the report! I think the right behavior should be to reduce ring size so that the issue doesn't happen. For now, please adjust size manually.
