### ISSUE TITLE
Fix Actions to skip S3 tests from external contributors

### ISSUE THREAD

**Issue by soldni** [allenai/dolma#27]
This would make the failures for #23 and #24 go away. 

Having external collaborators hit the test bucket is a security risk, so those tests should be skipped.

**Comment by chris-ha458** [comment]
This would be helpful!
Some reproducible and accessible data, even if it requires some work on the external collaborators part, could be a reasonable alternative as well.

Also, If S3 access is crucial even for outside cotnributors there are some world-readable-free aws buckets such as [PMC Open Access (OA) Subset on AWS](https://www.ncbi.nlm.nih.gov/pmc/tools/pmcaws/)  `s3://pmc-oa-opendata`
I am not sure if it is acceptable access to use it for this purpose. (If I had to guess it would be no)

**Comment by soldni** [comment]
That's an interesting idea! Some of the tests require buckets to be
writable, so we need to skip some anyway, but it would be nice to keep at
least some of the tests.

**Comment by chris-ha458** [comment]
Also is this issue that is blocking the assessment and merging of those two PRs at this time?
I am planning further commits upon those changes, if they cannot be integrated before this is addressed, I would rather assist in developing or testing this issue to help move things along.

**Comment by soldni** [comment]
@chris-ha458 I think the fixed I just merged in main should do it. if you have time to rebase, it would be great!

**Comment by soldni** [comment]
ok looks like it worked for #24 ! closing this issue.
