### ISSUE TITLE
Latest version is not on PyPi

### ISSUE THREAD

**Issue by KennethEnevoldsen** [allenai/dolma#78]
Seems like the latest version is not on PyPI. Seems like the CI skipped the release step.

**Comment by soldni** [comment]
Hi @KennethEnevoldsen ! The latest release (0.9.1) is on PyPI. I'm preparing the upcoming release, which should be out in the next few days. In the meantime, please install from github in case you want access to the latest features.

**Comment by KennethEnevoldsen** [comment]
Thanks @soldni ! We are currently installing from GitHub now. Will wait until the 0.9.2 is out

**Comment by soldni** [comment]
closing this issue now that the latest version has been pushed.
